name: GitHub Actions Example

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: self-hosted

    steps:
    
    - name: Switch to root and install packages
      run: |
        sudo -s <<EOF
        apt-get update
        EOF
